### ISSUE TITLE
Issues with app:androidJacocoAgent

### ISSUE THREAD

**Issue by AndrewReitz** [kaleidos/emerger#1]
When I add the plugin to the [groovy-android-sample](https://github.com/groovy/groovy-android-gradle-plugin/tree/master/groovy-android-sample-app) I recieve the following error.

```
 problem occurred configuring project ':groovy-android-sample-app'.
> Could not resolve all dependencies for configuration ':groovy-android-sample-app:androidJacocoAgent'.
   > Could not find org.jacoco:org.jacoco.agent:null.
     Searched in the following locations:
         https://jcenter.bintray.com/org/jacoco/org.jacoco.agent/null/org.jacoco.agent-null.pom
         https://jcenter.bintray.com/org/jacoco/org.jacoco.agent/null/org.jacoco.agent-null.jar
         file:/Users/areitz/Library/Android/sdk/extras/android/m2repository/org/jacoco/org.jacoco.agent/null/org.jacoco.agent-null.pom
         file:/Users/areitz/Library/Android/sdk/extras/android/m2repository/org/jacoco/org.jacoco.agent/null/org.jacoco.agent-null.jar
         file:/Users/areitz/Library/Android/sdk/extras/google/m2repository/org/jacoco/org.jacoco.agent/null/org.jacoco.agent-null.pom
         file:/Users/areitz/Library/Android/sdk/extras/google/m2repository/org/jacoco/org.jacoco.agent/null/org.jacoco.agent-null.jar
     Required by:
         org.codehaus.groovy:groovy-android-sample-app:0.3.8-SNAPSHOT
```

I followed the instructions on the README and this appears. I attempted to add jacoco and see the same or similar issue occurs.

**Comment by mariogarcia** [comment]
I remember experiencing this issue before with another old android/groovy project, but I can't remember it by heart. I think it had to do with android tools version. 

Anyway I'm looking into this

**Comment by AndrewReitz** [comment]
Cool thanks, let me know if you need any help.

**Comment by mariogarcia** [comment]
I've cloned the project in AS 1.5.1 and I was able to run the app right away.

- `Android Studio` 1.5.1
- `JDK` 1.7.0_80

**Comment by mariogarcia** [comment]
Now I'm getting the exception. Working on it.

**Comment by mariogarcia** [comment]
Weird, whereas in the plugin project it's failing, it doesn't fail in a brand new project. If I use the following dependencies in a new project it works:

```
dependencies {
    classpath 'com.android.tools.build:gradle:1.5.0' 
    classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:0.3.8-SNAPSHOT'
    classpath 'net.kaleidos.gradle.plugins:emerger:0.0.2'
}
```

The `emerger` plugin doesn't have any dependencies on jacoco neither uses it at compile time. I've made sure by executing `./gradlew dependencies`.

I think it has to do more with how you are managing plugin dependencies using the `buildSrc` folder as a way of making available `groovy-android-gradle-plugin` to the sample app.

I'll keep digging during the day. Things I would like to check:
- ~~Does it happen if we add any other plugin ?~~ groovysh plugin can be added withouth any issue
- Does it happen when the classpath of the sample-app is resolved the same way as above ?
- Where is supposed to be the jacoco version android plugin is expecting ?

I've done  some research about the latest topic and it seems android build plugin adds its own version of jacoco, in older versions of the plugin you were allowed to specify the jacoco version in the android configuration, but in the latest versions it forces you to specify the version in the `buildscript` block.

**Comment by AndrewReitz** [comment]
> Where is supposed to be the jacoco version android plugin is expecting ?

Android expects this (as of 1.4.0) to be included in the classpath. If I add 

```
dependencies {
  classpath 'com.android.tools.build:gradle:1.5.0' 
  classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:0.3.8-SNAPSHOT'
  classpath 'net.kaleidos.gradle.plugins:emerger:0.0.2'
  compile 'org.jacoco:jacoco:0.7.5.201505241946'
}
```

a very similar issue happens, I think the error message just has a version in it instead of null.

I was commenting out a lot of the `build.gradle` in the `buildSrc` directory since it messes with IntelliJ so hopefully that isn't what is causing this. I will try completely removing it and see what happens.

**Comment by AndrewReitz** [comment]
No clue why this is appearing in the sample, but just created a project with 0.3.9 of the Android plugin and added emerger and everything looks fine. I'm going to close this since I think it's just a strange issue that I will only see.

**Comment by mariogarcia** [comment]
Sorry I didn't have the time to look into it in the last month. Glad to hear that :+1:
